spring.application.name=SpringDemo
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5
spring.ai.openai.chat.options.temperature=1
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
